// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.29.3
// source: Api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpCode int32

const (
	OpCode_UNSPECIFIED  OpCode = 0
	OpCode_MATCH_START  OpCode = 1
	OpCode_MATCH_OVER   OpCode = 2
	OpCode_ROUND_START  OpCode = 3
	OpCode_PLAYER_READY OpCode = 4
	OpCode_PLAYER_TURN  OpCode = 5
	OpCode_PLAYER_ROLL  OpCode = 6
	OpCode_PLAYER_MOVE  OpCode = 7
	OpCode_PLAYER_CONF  OpCode = 8
	OpCode_PLAYER_FAIL  OpCode = 9
)

// Enum value maps for OpCode.
var (
	OpCode_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "MATCH_START",
		2: "MATCH_OVER",
		3: "ROUND_START",
		4: "PLAYER_READY",
		5: "PLAYER_TURN",
		6: "PLAYER_ROLL",
		7: "PLAYER_MOVE",
		8: "PLAYER_CONF",
		9: "PLAYER_FAIL",
	}
	OpCode_value = map[string]int32{
		"UNSPECIFIED":  0,
		"MATCH_START":  1,
		"MATCH_OVER":   2,
		"ROUND_START":  3,
		"PLAYER_READY": 4,
		"PLAYER_TURN":  5,
		"PLAYER_ROLL":  6,
		"PLAYER_MOVE":  7,
		"PLAYER_CONF":  8,
		"PLAYER_FAIL":  9,
	}
)

func (x OpCode) Enum() *OpCode {
	p := new(OpCode)
	*p = x
	return p
}

func (x OpCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpCode) Descriptor() protoreflect.EnumDescriptor {
	return file_Api_proto_enumTypes[0].Descriptor()
}

func (OpCode) Type() protoreflect.EnumType {
	return &file_Api_proto_enumTypes[0]
}

func (x OpCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpCode.Descriptor instead.
func (OpCode) EnumDescriptor() ([]byte, []int) {
	return file_Api_proto_rawDescGZIP(), []int{0}
}

type TileState int32

const (
	TileState_OPEN   TileState = 0
	TileState_TOGGLE TileState = 1
	TileState_SHUT   TileState = 2
)

// Enum value maps for TileState.
var (
	TileState_name = map[int32]string{
		0: "OPEN",
		1: "TOGGLE",
		2: "SHUT",
	}
	TileState_value = map[string]int32{
		"OPEN":   0,
		"TOGGLE": 1,
		"SHUT":   2,
	}
)

func (x TileState) Enum() *TileState {
	p := new(TileState)
	*p = x
	return p
}

func (x TileState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TileState) Descriptor() protoreflect.EnumDescriptor {
	return file_Api_proto_enumTypes[1].Descriptor()
}

func (TileState) Type() protoreflect.EnumType {
	return &file_Api_proto_enumTypes[1]
}

func (x TileState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TileState.Descriptor instead.
func (TileState) EnumDescriptor() ([]byte, []int) {
	return file_Api_proto_rawDescGZIP(), []int{1}
}

type PlayerState int32

const (
	PlayerState_IDLE PlayerState = 0
	PlayerState_ROLL PlayerState = 1
	PlayerState_PLAY PlayerState = 2
	PlayerState_FAIL PlayerState = 3
	PlayerState_DONE PlayerState = 4
)

// Enum value maps for PlayerState.
var (
	PlayerState_name = map[int32]string{
		0: "IDLE",
		1: "ROLL",
		2: "PLAY",
		3: "FAIL",
		4: "DONE",
	}
	PlayerState_value = map[string]int32{
		"IDLE": 0,
		"ROLL": 1,
		"PLAY": 2,
		"FAIL": 3,
		"DONE": 4,
	}
)

func (x PlayerState) Enum() *PlayerState {
	p := new(PlayerState)
	*p = x
	return p
}

func (x PlayerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerState) Descriptor() protoreflect.EnumDescriptor {
	return file_Api_proto_enumTypes[2].Descriptor()
}

func (PlayerState) Type() protoreflect.EnumType {
	return &file_Api_proto_enumTypes[2]
}

func (x PlayerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerState.Descriptor instead.
func (PlayerState) EnumDescriptor() ([]byte, []int) {
	return file_Api_proto_rawDescGZIP(), []int{2}
}

type MatchStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoundCount int32     `protobuf:"varint,1,opt,name=roundCount,proto3" json:"roundCount,omitempty"`
	TileCount  int32     `protobuf:"varint,2,opt,name=tileCount,proto3" json:"tileCount,omitempty"`
	TurnTime   int32     `protobuf:"varint,3,opt,name=turnTime,proto3" json:"turnTime,omitempty"`
	Players    []*Player `protobuf:"bytes,4,rep,name=players,proto3" json:"players,omitempty"`
}

func (x *MatchStart) Reset() {
	*x = MatchStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchStart) ProtoMessage() {}

func (x *MatchStart) ProtoReflect() protoreflect.Message {
	mi := &file_Api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchStart.ProtoReflect.Descriptor instead.
func (*MatchStart) Descriptor() ([]byte, []int) {
	return file_Api_proto_rawDescGZIP(), []int{0}
}

func (x *MatchStart) GetRoundCount() int32 {
	if x != nil {
		return x.RoundCount
	}
	return 0
}

func (x *MatchStart) GetTileCount() int32 {
	if x != nil {
		return x.TileCount
	}
	return 0
}

func (x *MatchStart) GetTurnTime() int32 {
	if x != nil {
		return x.TurnTime
	}
	return 0
}

func (x *MatchStart) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

type MatchOver struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Winner string        `protobuf:"bytes,1,opt,name=winner,proto3" json:"winner,omitempty"`
	Rounds []*RoundScore `protobuf:"bytes,2,rep,name=rounds,proto3" json:"rounds,omitempty"`
}

func (x *MatchOver) Reset() {
	*x = MatchOver{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchOver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchOver) ProtoMessage() {}

func (x *MatchOver) ProtoReflect() protoreflect.Message {
	mi := &file_Api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchOver.ProtoReflect.Descriptor instead.
func (*MatchOver) Descriptor() ([]byte, []int) {
	return file_Api_proto_rawDescGZIP(), []int{1}
}

func (x *MatchOver) GetWinner() string {
	if x != nil {
		return x.Winner
	}
	return ""
}

func (x *MatchOver) GetRounds() []*RoundScore {
	if x != nil {
		return x.Rounds
	}
	return nil
}

type RoundStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Interval int32       `protobuf:"varint,1,opt,name=interval,proto3" json:"interval,omitempty"`
	Score    *RoundScore `protobuf:"bytes,2,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *RoundStart) Reset() {
	*x = RoundStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoundStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundStart) ProtoMessage() {}

func (x *RoundStart) ProtoReflect() protoreflect.Message {
	mi := &file_Api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundStart.ProtoReflect.Descriptor instead.
func (*RoundStart) Descriptor() ([]byte, []int) {
	return file_Api_proto_rawDescGZIP(), []int{2}
}

func (x *RoundStart) GetInterval() int32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *RoundStart) GetScore() *RoundScore {
	if x != nil {
		return x.Score
	}
	return nil
}

type RoundScore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Players []string `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	Scores  []int32  `protobuf:"varint,2,rep,packed,name=scores,proto3" json:"scores,omitempty"`
}

func (x *RoundScore) Reset() {
	*x = RoundScore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoundScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundScore) ProtoMessage() {}

func (x *RoundScore) ProtoReflect() protoreflect.Message {
	mi := &file_Api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundScore.ProtoReflect.Descriptor instead.
func (*RoundScore) Descriptor() ([]byte, []int) {
	return file_Api_proto_rawDescGZIP(), []int{3}
}

func (x *RoundScore) GetPlayers() []string {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *RoundScore) GetScores() []int32 {
	if x != nil {
		return x.Scores
	}
	return nil
}

type PlayerTurn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
}

func (x *PlayerTurn) Reset() {
	*x = PlayerTurn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerTurn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerTurn) ProtoMessage() {}

func (x *PlayerTurn) ProtoReflect() protoreflect.Message {
	mi := &file_Api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerTurn.ProtoReflect.Descriptor instead.
func (*PlayerTurn) Descriptor() ([]byte, []int) {
	return file_Api_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerTurn) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type PlayerRoll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Roll     int32  `protobuf:"varint,2,opt,name=roll,proto3" json:"roll,omitempty"`
}

func (x *PlayerRoll) Reset() {
	*x = PlayerRoll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerRoll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerRoll) ProtoMessage() {}

func (x *PlayerRoll) ProtoReflect() protoreflect.Message {
	mi := &file_Api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerRoll.ProtoReflect.Descriptor instead.
func (*PlayerRoll) Descriptor() ([]byte, []int) {
	return file_Api_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerRoll) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerRoll) GetRoll() int32 {
	if x != nil {
		return x.Roll
	}
	return 0
}

type PlayerMove struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string    `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Index    int32     `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	State    TileState `protobuf:"varint,3,opt,name=state,proto3,enum=Api.TileState" json:"state,omitempty"`
}

func (x *PlayerMove) Reset() {
	*x = PlayerMove{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMove) ProtoMessage() {}

func (x *PlayerMove) ProtoReflect() protoreflect.Message {
	mi := &file_Api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMove.ProtoReflect.Descriptor instead.
func (*PlayerMove) Descriptor() ([]byte, []int) {
	return file_Api_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerMove) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerMove) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *PlayerMove) GetState() TileState {
	if x != nil {
		return x.State
	}
	return TileState_OPEN
}

type PlayerConfirm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string      `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Tiles    []TileState `protobuf:"varint,2,rep,packed,name=tiles,proto3,enum=Api.TileState" json:"tiles,omitempty"`
	BoxShut  bool        `protobuf:"varint,3,opt,name=boxShut,proto3" json:"boxShut,omitempty"`
}

func (x *PlayerConfirm) Reset() {
	*x = PlayerConfirm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerConfirm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerConfirm) ProtoMessage() {}

func (x *PlayerConfirm) ProtoReflect() protoreflect.Message {
	mi := &file_Api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerConfirm.ProtoReflect.Descriptor instead.
func (*PlayerConfirm) Descriptor() ([]byte, []int) {
	return file_Api_proto_rawDescGZIP(), []int{7}
}

func (x *PlayerConfirm) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerConfirm) GetTiles() []TileState {
	if x != nil {
		return x.Tiles
	}
	return nil
}

func (x *PlayerConfirm) GetBoxShut() bool {
	if x != nil {
		return x.BoxShut
	}
	return false
}

type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string      `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	State    PlayerState `protobuf:"varint,3,opt,name=State,proto3,enum=Api.PlayerState" json:"State,omitempty"`
	Roll     int32       `protobuf:"varint,2,opt,name=roll,proto3" json:"roll,omitempty"`
	Tiles    []TileState `protobuf:"varint,4,rep,packed,name=tiles,proto3,enum=Api.TileState" json:"tiles,omitempty"`
}

func (x *Player) Reset() {
	*x = Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_Api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_Api_proto_rawDescGZIP(), []int{8}
}

func (x *Player) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *Player) GetState() PlayerState {
	if x != nil {
		return x.State
	}
	return PlayerState_IDLE
}

func (x *Player) GetRoll() int32 {
	if x != nil {
		return x.Roll
	}
	return 0
}

func (x *Player) GetTiles() []TileState {
	if x != nil {
		return x.Tiles
	}
	return nil
}

var File_Api_proto protoreflect.FileDescriptor

var file_Api_proto_rawDesc = []byte{
	0x0a, 0x09, 0x41, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x41, 0x70, 0x69,
	0x22, 0x8d, 0x01, 0x0a, 0x0a, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12,
	0x1e, 0x0a, 0x0a, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x74, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x74, 0x75, 0x72, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x74, 0x75, 0x72, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x07, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x41, 0x70, 0x69,
	0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73,
	0x22, 0x4c, 0x0a, 0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x4f, 0x76, 0x65, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x77,
	0x69, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x41, 0x70, 0x69, 0x2e, 0x52, 0x6f, 0x75, 0x6e,
	0x64, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x06, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x22, 0x4f,
	0x0a, 0x0a, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x12, 0x25, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x41, 0x70, 0x69, 0x2e, 0x52, 0x6f,
	0x75, 0x6e, 0x64, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x22,
	0x3e, 0x0a, 0x0a, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x22,
	0x28, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x54, 0x75, 0x72, 0x6e, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3c, 0x0a, 0x0a, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x6c, 0x22, 0x64, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x24, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x41, 0x70, 0x69, 0x2e, 0x54, 0x69, 0x6c,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x6b, 0x0a,
	0x0d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x05, 0x74, 0x69,
	0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x41, 0x70, 0x69, 0x2e,
	0x54, 0x69, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x74, 0x69, 0x6c, 0x65, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x62, 0x6f, 0x78, 0x53, 0x68, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x62, 0x6f, 0x78, 0x53, 0x68, 0x75, 0x74, 0x22, 0x86, 0x01, 0x0a, 0x06, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x26, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x10, 0x2e, 0x41, 0x70, 0x69, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x6c, 0x12, 0x24, 0x0a,
	0x05, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x41,
	0x70, 0x69, 0x2e, 0x54, 0x69, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x74, 0x69,
	0x6c, 0x65, 0x73, 0x2a, 0xb2, 0x01, 0x0a, 0x06, 0x4f, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0f,
	0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x0f, 0x0a, 0x0b, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0x01,
	0x12, 0x0e, 0x0a, 0x0a, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x5f, 0x4f, 0x56, 0x45, 0x52, 0x10, 0x02,
	0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x4f, 0x55, 0x4e, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x10,
	0x03, 0x12, 0x10, 0x0a, 0x0c, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x52, 0x45, 0x41, 0x44,
	0x59, 0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x54, 0x55,
	0x52, 0x4e, 0x10, 0x05, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x52,
	0x4f, 0x4c, 0x4c, 0x10, 0x06, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f,
	0x4d, 0x4f, 0x56, 0x45, 0x10, 0x07, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52,
	0x5f, 0x43, 0x4f, 0x4e, 0x46, 0x10, 0x08, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x4c, 0x41, 0x59, 0x45,
	0x52, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x10, 0x09, 0x2a, 0x2b, 0x0a, 0x09, 0x54, 0x69, 0x6c, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4f, 0x50, 0x45, 0x4e, 0x10, 0x00, 0x12,
	0x0a, 0x0a, 0x06, 0x54, 0x4f, 0x47, 0x47, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x53,
	0x48, 0x55, 0x54, 0x10, 0x02, 0x2a, 0x3f, 0x0a, 0x0b, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x44, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x08,
	0x0a, 0x04, 0x52, 0x4f, 0x4c, 0x4c, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x4c, 0x41, 0x59,
	0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x41, 0x49, 0x4c, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04,
	0x44, 0x4f, 0x4e, 0x45, 0x10, 0x04, 0x42, 0x19, 0x5a, 0x17, 0x73, 0x68, 0x75, 0x74, 0x2d, 0x74,
	0x68, 0x65, 0x2d, 0x62, 0x6f, 0x78, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x61, 0x70,
	0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Api_proto_rawDescOnce sync.Once
	file_Api_proto_rawDescData = file_Api_proto_rawDesc
)

func file_Api_proto_rawDescGZIP() []byte {
	file_Api_proto_rawDescOnce.Do(func() {
		file_Api_proto_rawDescData = protoimpl.X.CompressGZIP(file_Api_proto_rawDescData)
	})
	return file_Api_proto_rawDescData
}

var file_Api_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_Api_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_Api_proto_goTypes = []interface{}{
	(OpCode)(0),           // 0: Api.OpCode
	(TileState)(0),        // 1: Api.TileState
	(PlayerState)(0),      // 2: Api.PlayerState
	(*MatchStart)(nil),    // 3: Api.MatchStart
	(*MatchOver)(nil),     // 4: Api.MatchOver
	(*RoundStart)(nil),    // 5: Api.RoundStart
	(*RoundScore)(nil),    // 6: Api.RoundScore
	(*PlayerTurn)(nil),    // 7: Api.PlayerTurn
	(*PlayerRoll)(nil),    // 8: Api.PlayerRoll
	(*PlayerMove)(nil),    // 9: Api.PlayerMove
	(*PlayerConfirm)(nil), // 10: Api.PlayerConfirm
	(*Player)(nil),        // 11: Api.Player
}
var file_Api_proto_depIdxs = []int32{
	11, // 0: Api.MatchStart.players:type_name -> Api.Player
	6,  // 1: Api.MatchOver.rounds:type_name -> Api.RoundScore
	6,  // 2: Api.RoundStart.score:type_name -> Api.RoundScore
	1,  // 3: Api.PlayerMove.state:type_name -> Api.TileState
	1,  // 4: Api.PlayerConfirm.tiles:type_name -> Api.TileState
	2,  // 5: Api.Player.State:type_name -> Api.PlayerState
	1,  // 6: Api.Player.tiles:type_name -> Api.TileState
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_Api_proto_init() }
func file_Api_proto_init() {
	if File_Api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchOver); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoundStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoundScore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerTurn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerRoll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerMove); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerConfirm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Api_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Api_proto_goTypes,
		DependencyIndexes: file_Api_proto_depIdxs,
		EnumInfos:         file_Api_proto_enumTypes,
		MessageInfos:      file_Api_proto_msgTypes,
	}.Build()
	File_Api_proto = out.File
	file_Api_proto_rawDesc = nil
	file_Api_proto_goTypes = nil
	file_Api_proto_depIdxs = nil
}
